--- #YAML:1.0
name:               URI-Dispatch
version:            v1.1
abstract:           determine which code to execute based upon path
author:
    - Mark Norman Francis <norm@cackhanded.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Message:    0
    Modern::Perl:     0
    MooseX::Declare:  0
    Ouch:             0
    Plack:            0
    version:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
